#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Musoq.Parser.Nodes;
using Musoq.Parser.Nodes.InterpretationSchema;

namespace Musoq.Evaluator.Visitors;

/// <summary>
///     Generates C# interpreter classes from binary and text schema AST nodes.
///     The generated classes inherit from BytesInterpreterBase or TextInterpreterBase
///     and implement the actual parsing logic.
/// </summary>
public class InterpreterCodeGenerator
{
    private readonly Dictionary<string, string> _generatedCode = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    ///     Tracks inline schema definitions that need nested class generation.
    ///     Key is the field name prefix (e.g., "Header"), value is the inline schema node.
    /// </summary>
    private readonly List<(string ClassName, InlineSchemaTypeNode Schema, string? ParentFieldPrefix)> _inlineSchemas =
        new();

    private readonly SchemaRegistry _registry;
    private string[] _currentTypeParameters = Array.Empty<string>();
    private int _discardCounter;

    /// <summary>
    ///     Creates a new interpreter code generator.
    /// </summary>
    /// <param name="registry">The schema registry containing schema definitions.</param>
    public InterpreterCodeGenerator(SchemaRegistry registry)
    {
        _registry = registry ?? throw new ArgumentNullException(nameof(registry));
    }

    /// <summary>
    ///     Gets the generated source code for all schemas.
    ///     Key is schema name, value is the C# source code.
    /// </summary>
    public IReadOnlyDictionary<string, string> GeneratedCode => _generatedCode;

    /// <summary>
    ///     Generates C# code for all schemas in the registry.
    /// </summary>
    /// <param name="namespaceName">The namespace for the generated classes.</param>
    /// <returns>Complete C# source code containing all generated interpreter classes.</returns>
    public string GenerateAll(string namespaceName = "Musoq.Generated.Interpreters")
    {
        var builder = new StringBuilder();


        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("// This code was generated by Musoq Interpretation Schema code generator.");
        builder.AppendLine("// Do not modify this file directly.");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Buffers.Binary;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Dynamic;");
        builder.AppendLine("using Musoq.Schema.Interpreters;");
        builder.AppendLine();
        builder.AppendLine($"namespace {namespaceName}");
        builder.AppendLine("{");

        foreach (var registration in _registry.Schemas)
            if (registration.Node is BinarySchemaNode binarySchema)
            {
                _inlineSchemas.Clear();
                var classCode = GenerateBinaryInterpreterClass(binarySchema);
                _generatedCode[registration.Name] = classCode;
                builder.AppendLine(Indent(classCode, 1));
                builder.AppendLine();

                
                foreach (var (inlineClassName, inlineSchema, _) in _inlineSchemas)
                {
                    var inlineClassCode = GenerateInlineSchemaNestedClass(inlineClassName, inlineSchema);
                    builder.AppendLine(Indent(inlineClassCode, 1));
                    builder.AppendLine();
                }
            }
            else if (registration.Node is TextSchemaNode textSchema)
            {
                var classCode = GenerateTextInterpreterClass(textSchema);
                _generatedCode[registration.Name] = classCode;
                builder.AppendLine(Indent(classCode, 1));
                builder.AppendLine();
            }

        builder.AppendLine("}");

        return builder.ToString();
    }

    private string GenerateBinaryInterpreterClass(BinarySchemaNode schema)
    {
        var builder = new StringBuilder();
        var className = schema.Name;


        _inlineSchemas.Clear();
        _discardCounter = 0;


        _currentTypeParameters = schema.TypeParameters ?? Array.Empty<string>();
        var typeParameters = _currentTypeParameters;


        var typeParamsDecl = schema.IsGeneric
            ? $"<{string.Join(", ", typeParameters)}>"
            : string.Empty;
        var fullClassName = $"{className}{typeParamsDecl}";


        var genericConstraints = string.Empty;
        if (schema.IsGeneric)
        {
            var constraints = typeParameters
                .Select(t => $"where {t} : IBytesInterpreter<{t}>, new()")
                .ToArray();
            genericConstraints = " " + string.Join(" ", constraints);
        }


        var allFields = GetAllFieldsIncludingInherited(schema);


        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// Generated interpreter for binary schema '{className}'.");
        if (schema.IsGeneric)
            builder.AppendLine(
                $"/// This is a generic schema with type parameters: {string.Join(", ", typeParameters)}.");
        if (!string.IsNullOrEmpty(schema.Extends)) builder.AppendLine($"/// Extends schema '{schema.Extends}'.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine(
            $"public sealed class {fullClassName} : BytesInterpreterBase<{fullClassName}>{genericConstraints}");
        builder.AppendLine("{");


        foreach (var field in allFields)
        {
            if (field.Name == "_") continue;


            if (field is FieldDefinitionNode { TypeAnnotation: AlignmentNode }) continue;

            var clrTypeName = GetClrTypeNameForFieldWithContext(field, allFields);
            var isConditional = field.IsConditional;
            var isTypeParam = IsTypeParameter(clrTypeName);


            var propertyTypeName = isConditional && !IsReferenceType(clrTypeName) && !isTypeParam
                ? $"{clrTypeName}?"
                : clrTypeName;

            var escapedFieldName = EscapeCSharpIdentifier(field.Name);
            builder.AppendLine($"    /// <summary>Gets the {field.Name} field value.</summary>");
            builder.AppendLine($"    public {propertyTypeName} {escapedFieldName} {{ get; init; }}");
            builder.AppendLine();
        }


        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine($"    public override string SchemaName => \"{className}\";");
        builder.AppendLine();


        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine($"    public override {fullClassName} InterpretAt(ReadOnlySpan<byte> data, int offset)");
        builder.AppendLine("    {");
        builder.AppendLine("        _parsePosition = offset;");
        builder.AppendLine("        BitOffset = 0;");
        builder.AppendLine();


        var fieldInitializers = new List<string>();
        foreach (var field in allFields)
            switch (field)
            {
                case FieldDefinitionNode parsedField:
                {
                    var readCode = GenerateFieldReadCodeWithModifiers(parsedField);
                    builder.Append(Indent(readCode, 2));

                    if (parsedField.Name != "_" && parsedField.TypeAnnotation is not AlignmentNode)
                        fieldInitializers.Add($"{EscapeCSharpIdentifier(parsedField.Name)} = {GetLocalVarName(parsedField.Name)}");
                    break;
                }
                case ComputedFieldNode computedField:
                {
                    var computeCode = GenerateComputedFieldCode(computedField, allFields);
                    builder.Append(Indent(computeCode, 2));

                    if (computedField.Name != "_")
                        fieldInitializers.Add($"{EscapeCSharpIdentifier(computedField.Name)} = {GetLocalVarName(computedField.Name)}");
                    break;
                }
            }


        builder.AppendLine($"        return new {fullClassName}");
        builder.AppendLine("        {");
        for (var i = 0; i < fieldInitializers.Count; i++)
        {
            var comma = i < fieldInitializers.Count - 1 ? "," : "";
            builder.AppendLine($"            {fieldInitializers[i]}{comma}");
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");

        builder.AppendLine("}");

        return builder.ToString();
    }

    private string GenerateInlineSchemaNestedClass(string className, InlineSchemaTypeNode inlineSchema)
    {
        var builder = new StringBuilder();
        var outerRefs = CollectOuterFieldReferences(inlineSchema);

        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// Generated nested interpreter for inline schema '{className}'.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine($"public sealed class {className} : BytesInterpreterBase<{className}>");
        builder.AppendLine("{");


        var fields = inlineSchema.Fields;
        foreach (var field in fields)
        {
            if (field.Name == "_") continue;

            if (field is FieldDefinitionNode { TypeAnnotation: AlignmentNode }) continue;

            var clrTypeName = GetClrTypeNameForFieldInline(field);
            var isConditional = field.IsConditional;
            var isTypeParam = IsTypeParameter(clrTypeName);

            var propertyTypeName = isConditional && !IsReferenceType(clrTypeName) && !isTypeParam
                ? $"{clrTypeName}?"
                : clrTypeName;

            builder.AppendLine($"    /// <summary>Gets the {field.Name} field value.</summary>");
            builder.AppendLine($"    public {propertyTypeName} {EscapeCSharpIdentifier(field.Name)} {{ get; init; }}");
            builder.AppendLine();
        }

        
        foreach (var outerRef in outerRefs)
        {
            builder.AppendLine($"    /// <summary>Outer scope reference for '{outerRef}'.</summary>");
            builder.AppendLine($"    internal int Outer{EscapeCSharpIdentifier(outerRef)} {{ get; set; }}");
            builder.AppendLine();
        }

        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine($"    public override string SchemaName => \"{className}\";");
        builder.AppendLine();


        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine($"    public override {className} InterpretAt(ReadOnlySpan<byte> data, int offset)");
        builder.AppendLine("    {");
        builder.AppendLine("        _parsePosition = offset;");
        builder.AppendLine("        BitOffset = 0;");
        builder.AppendLine();

        
        foreach (var outerRef in outerRefs)
        {
            var localVar = GetLocalVarName(outerRef);
            builder.AppendLine($"        var {localVar} = Outer{EscapeCSharpIdentifier(outerRef)};");
        }

        if (outerRefs.Count > 0)
            builder.AppendLine();

        var fieldInitializers = new List<string>();
        foreach (var field in fields)
        {
            if (field is not FieldDefinitionNode parsedField) continue;

            var readCode = GenerateFieldReadCodeWithModifiers(parsedField);
            builder.Append(Indent(readCode, 2));

            if (parsedField.Name != "_" && parsedField.TypeAnnotation is not AlignmentNode)
                fieldInitializers.Add($"{EscapeCSharpIdentifier(parsedField.Name)} = {GetLocalVarName(parsedField.Name)}");
        }


        builder.AppendLine($"        return new {className}");
        builder.AppendLine("        {");
        for (var i = 0; i < fieldInitializers.Count; i++)
        {
            var comma = i < fieldInitializers.Count - 1 ? "," : "";
            builder.AppendLine($"            {fieldInitializers[i]}{comma}");
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");

        builder.AppendLine("}");

        return builder.ToString();
    }

    private string GetClrTypeNameForFieldInline(SchemaFieldNode field)
    {
        return field switch
        {
            FieldDefinitionNode parsedField when parsedField.TypeAnnotation is InlineSchemaTypeNode nestedInline
                => GetOrRegisterInlineSchemaClassName(parsedField.Name, nestedInline, null),
            FieldDefinitionNode parsedField => GetClrTypeName(parsedField.TypeAnnotation),
            ComputedFieldNode computedField => InferComputedFieldTypeNameStatic(computedField.Expression),
            _ => "object"
        };
    }

    private List<SchemaFieldNode> GetAllFieldsIncludingInherited(BinarySchemaNode schema)
    {
        if (string.IsNullOrEmpty(schema.Extends))
            return schema.Fields.ToList();

        var allFields = new List<SchemaFieldNode>();

        if (!string.IsNullOrEmpty(schema.Extends))
        {
            var parentSchema = _registry.Schemas
                .FirstOrDefault(s => s.Name.Equals(schema.Extends, StringComparison.OrdinalIgnoreCase));

            if (parentSchema?.Node is BinarySchemaNode parentBinarySchema)
                allFields.AddRange(GetAllFieldsIncludingInherited(parentBinarySchema));
        }

        
        var overriddenParentNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var childField in schema.Fields)
        {
            for (var i = 0; i < allFields.Count; i++)
            {
                if (string.Equals(allFields[i].Name, childField.Name, StringComparison.OrdinalIgnoreCase))
                {
                    allFields[i] = childField;
                    overriddenParentNames.Add(childField.Name);
                    break;
                }
            }
        }

        
        foreach (var childField in schema.Fields)
        {
            if (!overriddenParentNames.Contains(childField.Name))
                allFields.Add(childField);
        }

        return allFields;
    }

    private string GenerateFieldReadCodeWithModifiers(FieldDefinitionNode field)
    {
        var builder = new StringBuilder();
        var localVar = GetLocalVarName(field.Name);
        var clrTypeName = GetClrTypeNameForFieldDefinition(field);


        if (field.WhenCondition != null)
        {
            var condition = GenerateConditionExpression(field.WhenCondition);
            var isTypeParam = IsTypeParameter(clrTypeName);
            var isReferenceType = IsReferenceType(clrTypeName);


            string nullableTypeName;
            string defaultValue;

            if (isTypeParam)
            {
                nullableTypeName = clrTypeName;
                defaultValue = "default!";
            }
            else if (isReferenceType)
            {
                nullableTypeName = clrTypeName;
                defaultValue = "null";
            }
            else
            {
                nullableTypeName = $"{clrTypeName}?";
                defaultValue = "null";
            }


            builder.AppendLine($"{nullableTypeName} {localVar} = {defaultValue};");
            builder.AppendLine($"if ({condition})");
            builder.AppendLine("{");


            if (field.AtOffset != null)
            {
                var offsetExpr = GenerateConditionExpression(field.AtOffset);
                builder.AppendLine($"    _parsePosition = {offsetExpr};");
            }


            var innerReadCode = GenerateFieldReadCodeInner(field, localVar);
            builder.Append(Indent(innerReadCode, 1));


            if (field.Constraint != null)
            {
                var checkExpr = GenerateConditionExpression(field.Constraint.Expression);
                builder.AppendLine($"    Validate({checkExpr}, \"{field.Name}\", \"Check constraint failed\");");
            }

            builder.AppendLine("}");
        }
        else
        {
            if (field.AtOffset != null)
            {
                var offsetExpr = GenerateConditionExpression(field.AtOffset);
                builder.AppendLine($"_parsePosition = {offsetExpr};");
            }


            builder.AppendLine(GenerateFieldReadCode(field));


            if (field.Constraint != null)
            {
                var checkExpr = GenerateConditionExpression(field.Constraint.Expression);
                builder.AppendLine($"Validate({checkExpr}, \"{field.Name}\", \"Check constraint failed\");");
            }
        }

        return builder.ToString();
    }

    private string GenerateFieldReadCodeInner(FieldDefinitionNode field, string? overrideLocalVar = null)
    {
        var builder = new StringBuilder();
        var localVar = overrideLocalVar ?? GetLocalVarName(field.Name);
        var typeAnnotation = field.TypeAnnotation;

        switch (typeAnnotation)
        {
            case PrimitiveTypeNode primitiveType:
                builder.AppendLine($"{localVar} = {GetPrimitiveReadMethod(primitiveType)}(data);");
                break;

            case ByteArrayTypeNode byteArrayType:
                var byteSize = GenerateSizeExpression(byteArrayType.SizeExpression);
                builder.AppendLine($"{localVar} = ReadBytes(data, {byteSize});");
                break;

            case StringTypeNode stringType:
                var strSize = GenerateSizeExpression(stringType.SizeExpression);
                var encodingExpr = GetEncodingExpression(stringType.Encoding);


                if (stringType.AsTextSchemaName != null)
                {
                    var rawStringVar = $"{localVar}_raw";
                    if (stringType.Modifiers.HasFlag(StringModifier.NullTerm))
                        builder.Append(
                            $"var {rawStringVar} = ReadNullTerminatedString(data, {strSize}, {encodingExpr})");
                    else
                        builder.Append($"var {rawStringVar} = ReadString(data, {strSize}, {encodingExpr})");


                    if (stringType.Modifiers.HasFlag(StringModifier.Trim))
                        builder.Append(".Trim()");
                    else if (stringType.Modifiers.HasFlag(StringModifier.LTrim))
                        builder.Append(".TrimStart()");
                    else if (stringType.Modifiers.HasFlag(StringModifier.RTrim))
                        builder.Append(".TrimEnd()");

                    builder.AppendLine(";");
                    builder.AppendLine($"var {localVar}_textInterpreter = new {stringType.AsTextSchemaName}();");
                    builder.AppendLine($"{localVar} = {localVar}_textInterpreter.Parse({rawStringVar});");
                }
                else
                {
                    if (stringType.Modifiers.HasFlag(StringModifier.NullTerm))
                        builder.Append($"{localVar} = ReadNullTerminatedString(data, {strSize}, {encodingExpr})");
                    else
                        builder.Append($"{localVar} = ReadString(data, {strSize}, {encodingExpr})");


                    if (stringType.Modifiers.HasFlag(StringModifier.Trim))
                        builder.Append(".Trim()");
                    else if (stringType.Modifiers.HasFlag(StringModifier.LTrim))
                        builder.Append(".TrimStart()");
                    else if (stringType.Modifiers.HasFlag(StringModifier.RTrim))
                        builder.Append(".TrimEnd()");

                    builder.AppendLine(";");
                }

                break;

            case BitsTypeNode bitsType:
                var innerBitCount = bitsType.BitCount;
                var bitsCastType = GetBitsClrTypeName(bitsType);
                builder.AppendLine($"{localVar} = ({bitsCastType})ReadBits(data, {innerBitCount});");
                break;

            case SchemaReferenceTypeNode schemaRef:
                builder.AppendLine($"var {localVar}_interpreter = new {schemaRef.SchemaName}();");
                builder.AppendLine($"{localVar} = {localVar}_interpreter.InterpretAt(data, _parsePosition);");
                builder.AppendLine($"_parsePosition = {localVar}_interpreter.BytesConsumed;");
                break;

            case ArrayTypeNode arrayType:
                var arraySizeExpr = GenerateSizeExpression(arrayType.SizeExpression);
                var elementTypeName = GetClrTypeName(arrayType.ElementType);
                var loopVarInner = $"_{localVar}_i";
                builder.AppendLine($"{localVar} = new {elementTypeName}[{arraySizeExpr}];");
                builder.AppendLine($"for (int {loopVarInner} = 0; {loopVarInner} < {arraySizeExpr}; {loopVarInner}++)");
                builder.AppendLine("{");

                if (arrayType.ElementType is PrimitiveTypeNode elemPrimitive)
                {
                    builder.AppendLine($"    {localVar}[{loopVarInner}] = {GetPrimitiveReadMethod(elemPrimitive)}(data);");
                }
                else if (arrayType.ElementType is SchemaReferenceTypeNode elemSchemaRef)
                {
                    var elemSchemaName = elemSchemaRef.SchemaName;
                    var elemInterpreterVar = $"_{localVar}_elem_interpreter";
                    builder.AppendLine($"    var {elemInterpreterVar} = new {elemSchemaName}();");
                    builder.AppendLine($"    {localVar}[{loopVarInner}] = {elemInterpreterVar}.InterpretAt(data, _parsePosition);");
                    builder.AppendLine($"    _parsePosition = {elemInterpreterVar}.BytesConsumed;");
                }
                else
                {
                    builder.AppendLine(
                        $"    // TODO: Unsupported array element type: {arrayType.ElementType.GetType().Name}");
                }

                builder.AppendLine("}");
                break;

            case AlignmentNode alignmentNode:
                builder.AppendLine($"AlignToBits(data, {alignmentNode.AlignmentBits});");
                break;

            case InlineSchemaTypeNode inlineSchema:

                var inlineClassName = GetOrRegisterInlineSchemaClassName(field.Name, inlineSchema, null);
                builder.AppendLine($"var {localVar}_interpreter = new {inlineClassName}();");
                builder.Append(GenerateOuterRefAssignments($"{localVar}_interpreter", inlineSchema));
                builder.AppendLine($"{localVar} = {localVar}_interpreter.InterpretAt(data, _parsePosition);");
                builder.AppendLine($"_parsePosition = {localVar}_interpreter.BytesConsumed;");
                break;

            default:
                builder.AppendLine($"// TODO: Unsupported type annotation: {typeAnnotation.GetType().Name}");
                if (field.Name != "_") builder.AppendLine($"{localVar} = default({GetClrTypeName(typeAnnotation)})!;");
                break;
        }

        return builder.ToString();
    }

    private string GenerateTextInterpreterClass(TextSchemaNode schema)
    {
        var builder = new StringBuilder();
        var className = schema.Name;
        _discardCounter = 0;

        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// Generated interpreter for text schema '{className}'.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine($"public sealed class {className} : TextInterpreterBase<{className}>");
        builder.AppendLine("{");


        foreach (var field in schema.Fields)
        {
            if (field.IsDiscard) continue;

            
            if (field.FieldType == TextFieldType.Pattern && field.CaptureGroups.Length > 0)
            {
                builder.AppendLine($"    /// <summary>Gets the {field.Name} capture result.</summary>");
                builder.AppendLine($"    public CaptureResult_{field.Name}? {EscapeCSharpIdentifier(field.Name)} {{ get; init; }}");
                builder.AppendLine();
                continue;
            }

            builder.AppendLine($"    /// <summary>Gets the {field.Name} field value.</summary>");


            if (field.FieldType == TextFieldType.Repeat)
            {
                var schemaName = field.PrimaryValue ?? "object";
                builder.AppendLine($"    public {schemaName}[]? {EscapeCSharpIdentifier(field.Name)} {{ get; init; }}");
            }

            else if (field.FieldType == TextFieldType.Switch)
            {
                builder.AppendLine($"    public object? {EscapeCSharpIdentifier(field.Name)} {{ get; init; }}");
            }
            else
            {
                builder.AppendLine($"    public string? {EscapeCSharpIdentifier(field.Name)} {{ get; init; }}");
            }

            builder.AppendLine();
        }

        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine($"    public override string SchemaName => \"{className}\";");
        builder.AppendLine();

        builder.AppendLine("    /// <inheritdoc />");
        builder.AppendLine($"    public override {className} ParseAt(ReadOnlySpan<char> data, int offset)");
        builder.AppendLine("    {");
        builder.AppendLine("        _parsePosition = offset;");
        builder.AppendLine();


        var fieldInitializers = new List<string>();
        var fieldsList = schema.Fields.ToList();
        for (var i = 0; i < fieldsList.Count; i++)
        {
            var field = fieldsList[i];
            var nextField = i < fieldsList.Count - 1 ? fieldsList[i + 1] : null;
            var readCode = GenerateTextFieldReadCode(field, nextField);
            builder.Append(Indent(readCode, 2));

            if (!field.IsDiscard)
                fieldInitializers.Add($"{EscapeCSharpIdentifier(field.Name)} = {GetLocalVarName(field.Name)}");
        }


        builder.AppendLine($"        return new {className}");
        builder.AppendLine("        {");
        for (var i = 0; i < fieldInitializers.Count; i++)
        {
            var comma = i < fieldInitializers.Count - 1 ? "," : "";
            builder.AppendLine($"            {fieldInitializers[i]}{comma}");
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");

        
        foreach (var field in schema.Fields)
        {
            if (field.IsDiscard) continue;
            if (field.FieldType != TextFieldType.Pattern || field.CaptureGroups.Length == 0) continue;

            builder.AppendLine();
            builder.AppendLine($"    public sealed class CaptureResult_{field.Name}");
            builder.AppendLine("    {");
            foreach (var group in field.CaptureGroups)
            {
                builder.AppendLine($"        public string? {group} {{ get; init; }}");
            }
            builder.AppendLine("    }");
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    private string GenerateTextFieldReadCode(TextFieldDefinitionNode field, TextFieldDefinitionNode? nextField)
    {
        var builder = new StringBuilder();
        var localVar = GetLocalVarName(field.Name);
        var isDiscard = field.IsDiscard;
        var isOptional = (field.Modifiers & TextFieldModifier.Optional) != 0;
        var hasLower = (field.Modifiers & TextFieldModifier.Lower) != 0;
        var hasUpper = (field.Modifiers & TextFieldModifier.Upper) != 0;


        if (isOptional && !isDiscard)
        {
            builder.AppendLine($"string? {localVar} = null;");
            builder.AppendLine($"var _savedPos_{localVar} = _parsePosition;");
            builder.AppendLine("try");
            builder.AppendLine("{");
            builder.Append("    ");
            builder.AppendLine(GenerateTextFieldReadCodeInner(field, $"_temp_{localVar}", false, nextField));
            builder.AppendLine($"    {localVar} = _temp_{localVar};");
            builder.AppendLine("}");
            builder.AppendLine("catch");
            builder.AppendLine("{");
            builder.AppendLine($"    _parsePosition = _savedPos_{localVar};");
            builder.AppendLine("}");
        }
        else if (isOptional && isDiscard)
        {
            var discardId = Guid.NewGuid().ToString("N")[..8];
            builder.AppendLine($"var _savedPos_{discardId} = _parsePosition;");
            builder.AppendLine("try");
            builder.AppendLine("{");
            builder.Append("    ");
            builder.AppendLine(GenerateTextFieldReadCodeInner(field, "_", true, nextField));
            builder.AppendLine("}");
            builder.AppendLine("catch");
            builder.AppendLine("{");
            builder.AppendLine($"    _parsePosition = _savedPos_{discardId};");
            builder.AppendLine("}");
        }
        else
        {
            builder.AppendLine(GenerateTextFieldReadCodeInner(field, localVar, isDiscard, nextField));
        }

        
        if (!isDiscard && (hasLower || hasUpper) && field.FieldType != TextFieldType.Repeat && field.FieldType != TextFieldType.Switch)
        {
            if (hasLower)
                builder.AppendLine($"{localVar} = {localVar}?.ToLowerInvariant();");
            else if (hasUpper)
                builder.AppendLine($"{localVar} = {localVar}?.ToUpperInvariant();");
        }

        return builder.ToString();
    }

    private string GenerateTextFieldReadCodeInner(TextFieldDefinitionNode field, string localVar, bool isDiscard,
        TextFieldDefinitionNode? nextField)
    {
        return field.FieldType switch
        {
            TextFieldType.Literal => GenerateLiteralCode(field),
            TextFieldType.Until => GenerateUntilCode(field, localVar, isDiscard, nextField),
            TextFieldType.Between => GenerateBetweenCode(field, localVar, isDiscard),
            TextFieldType.Chars => GenerateCharsCode(field, localVar, isDiscard),
            TextFieldType.Token => GenerateTokenCode(field, localVar, isDiscard),
            TextFieldType.Rest => GenerateRestCode(field, localVar, isDiscard),
            TextFieldType.Whitespace => GenerateWhitespaceCode(field),
            TextFieldType.Pattern => GeneratePatternCode(field, localVar, isDiscard),
            TextFieldType.Repeat => GenerateRepeatCode(field, localVar, isDiscard),
            TextFieldType.Switch => GenerateSwitchCode(field, localVar, isDiscard),
            _ => throw new NotSupportedException($"Text field type '{field.FieldType}' is not yet supported.")
        };
    }

    private string GenerateLiteralCode(TextFieldDefinitionNode field)
    {
        var escapedLiteral = EscapeCSharpString(field.PrimaryValue ?? string.Empty);
        return $"ExpectLiteral(data, \"{escapedLiteral}\");";
    }

    private string GenerateUntilCode(TextFieldDefinitionNode field, string localVar, bool isDiscard,
        TextFieldDefinitionNode? nextField)
    {
        var escapedDelimiter = EscapeCSharpString(field.PrimaryValue ?? string.Empty);
        var hasTrim = (field.Modifiers & TextFieldModifier.Trim) != 0;
        var trimArg = hasTrim ? ", trim: true" : "";


        var shouldNotConsume = nextField is { FieldType: TextFieldType.Between }
                               && string.Equals(field.PrimaryValue, nextField.PrimaryValue, StringComparison.Ordinal);
        var consumeArg = shouldNotConsume ? ", consumeDelimiter: false" : "";

        if (isDiscard) return $"_ = ReadUntil(data, \"{escapedDelimiter}\"{trimArg}{consumeArg});";
        return $"var {localVar} = ReadUntil(data, \"{escapedDelimiter}\"{trimArg}{consumeArg});";
    }

    private string GenerateBetweenCode(TextFieldDefinitionNode field, string localVar, bool isDiscard)
    {
        var escapedOpen = EscapeCSharpString(field.PrimaryValue ?? string.Empty);
        var escapedClose = EscapeCSharpString(field.SecondaryValue ?? string.Empty);
        var nested = (field.Modifiers & TextFieldModifier.Nested) != 0 ? ", nested: true" : "";
        var hasTrim = (field.Modifiers & TextFieldModifier.Trim) != 0;
        var trimArg = hasTrim ? ", trim: true" : "";
        var hasEscaped = (field.Modifiers & TextFieldModifier.Escaped) != 0;
        var escapedArg = hasEscaped ? ", escaped: true" : "";

        if (isDiscard) return $"_ = ReadBetween(data, \"{escapedOpen}\", \"{escapedClose}\"{nested}{trimArg}{escapedArg});";
        return $"var {localVar} = ReadBetween(data, \"{escapedOpen}\", \"{escapedClose}\"{nested}{trimArg}{escapedArg});";
    }

    private string GenerateCharsCode(TextFieldDefinitionNode field, string localVar, bool isDiscard)
    {
        var count = field.PrimaryValue ?? "0";
        var modArgs = GenerateModifierArgs(field.Modifiers);

        if (isDiscard) return $"_ = ReadChars(data, {count}{modArgs});";
        return $"var {localVar} = ReadChars(data, {count}{modArgs});";
    }

    private string GenerateTokenCode(TextFieldDefinitionNode field, string localVar, bool isDiscard)
    {
        var hasTrim = (field.Modifiers & TextFieldModifier.Trim) != 0;
        var trimArg = hasTrim ? ", trim: true" : "";

        if (isDiscard) return $"_ = ReadToken(data{trimArg});";
        return $"var {localVar} = ReadToken(data{trimArg});";
    }

    private string GenerateRestCode(TextFieldDefinitionNode field, string localVar, bool isDiscard)
    {
        var modArgs = GenerateModifierArgs(field.Modifiers);

        if (isDiscard) return $"_ = ReadRest(data{modArgs});";
        return $"var {localVar} = ReadRest(data{modArgs});";
    }

    private string GenerateWhitespaceCode(TextFieldDefinitionNode field)
    {
        var quantifier = field.PrimaryValue ?? "+";

        return quantifier switch
        {
            "+" => "SkipWhitespace(data, true);",
            "*" => "SkipWhitespace(data, false);",
            "?" => "SkipOptionalWhitespace(data);",
            _ => "SkipWhitespace(data, true);"
        };
    }

    private string GeneratePatternCode(TextFieldDefinitionNode field, string localVar, bool isDiscard)
    {
        var escapedPattern = EscapeCSharpRegexString(field.PrimaryValue ?? string.Empty);

        if (field.CaptureGroups.Length > 0 && !isDiscard)
        {
            
            var builder = new StringBuilder();
            var matchVar = $"_match_{localVar}";
            var captureClassName = $"CaptureResult_{field.Name}";
            builder.AppendLine($"var {matchVar} = ReadPatternMatch(data, @\"{escapedPattern}\");");
            builder.Append($"var {localVar} = {matchVar}.Success ? new {captureClassName} {{ ");
            var groupInits = new List<string>();
            foreach (var group in field.CaptureGroups)
                groupInits.Add($"{group} = {matchVar}.Groups[\"{group}\"].Value");
            builder.Append(string.Join(", ", groupInits));
            builder.AppendLine($" }} : null;");
            return builder.ToString();
        }

        if (isDiscard) return $"_ = ReadPattern(data, @\"{escapedPattern}\");";
        return $"var {localVar} = ReadPattern(data, @\"{escapedPattern}\");";
    }

    private string GenerateRepeatCode(TextFieldDefinitionNode field, string localVar, bool isDiscard)
    {
        var schemaName = field.PrimaryValue ??
                         throw new InvalidOperationException("Repeat field must specify a schema name");
        var untilDelimiter = field.SecondaryValue;

        var builder = new StringBuilder();
        var listVar = $"_list_{localVar}";
        var itemVar = $"_item_{localVar}";
        var interpreterVar = $"_interp_{schemaName}";


        builder.AppendLine($"var {listVar} = new System.Collections.Generic.List<{schemaName}>();");
        builder.AppendLine($"var {interpreterVar} = new {schemaName}();");

        if (untilDelimiter != null)
        {
            var escapedDelimiter = EscapeCSharpString(untilDelimiter);
            builder.AppendLine($"while (!IsAtEnd(data) && !LookaheadMatches(data, \"{escapedDelimiter}\"))");
            builder.AppendLine("{");
            builder.AppendLine($"    var {itemVar} = {interpreterVar}.ParseAt(data, _parsePosition);");
            builder.AppendLine($"    _parsePosition = {interpreterVar}.Position;");
            builder.AppendLine($"    {listVar}.Add({itemVar});");
            builder.AppendLine("}");

            builder.AppendLine($"if (LookaheadMatches(data, \"{escapedDelimiter}\"))");
            builder.AppendLine("{");
            builder.AppendLine($"    _parsePosition += {untilDelimiter.Length};");
            builder.AppendLine("}");
        }
        else
        {
            builder.AppendLine("while (!IsAtEnd(data))");
            builder.AppendLine("{");
            builder.AppendLine($"    var {itemVar} = {interpreterVar}.ParseAt(data, _parsePosition);");
            builder.AppendLine($"    _parsePosition = {interpreterVar}.Position;");
            builder.AppendLine($"    {listVar}.Add({itemVar});");
            builder.AppendLine("}");
        }


        if (isDiscard)
            builder.AppendLine($"_ = {listVar}.ToArray();");
        else
            builder.AppendLine($"var {localVar} = {listVar}.ToArray();");

        return builder.ToString();
    }

    private string GenerateSwitchCode(TextFieldDefinitionNode field, string localVar, bool isDiscard)
    {
        var builder = new StringBuilder();

        if (field.SwitchCases.Length == 0)
            throw new InvalidOperationException("Switch field must have at least one case");

        
        var allProperties = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var switchCase in field.SwitchCases)
        {
            var schemaName = switchCase.TypeName;
            var schema = _registry.Schemas.FirstOrDefault(s =>
                string.Equals(s.Name, schemaName, StringComparison.OrdinalIgnoreCase));
            if (schema?.Node is TextSchemaNode textNode)
            {
                foreach (var f in textNode.Fields)
                {
                    if (!f.IsDiscard) allProperties.Add(f.Name);
                }
            }
        }

        
        var expandoVar = $"_{localVar}_expando";
        var dictVar = $"_{localVar}_dict";
        builder.AppendLine($"var {expandoVar} = new System.Dynamic.ExpandoObject();");
        builder.AppendLine($"var {dictVar} = (System.Collections.Generic.IDictionary<string, object?>){expandoVar};");
        foreach (var prop in allProperties)
        {
            builder.AppendLine($"{dictVar}[\"{prop}\"] = null;");
        }

        var isFirstCase = true;
        TextSwitchCaseNode? defaultCase = null;

        foreach (var switchCase in field.SwitchCases)
        {
            if (switchCase.IsDefault)
            {
                defaultCase = switchCase;
                continue;
            }

            var escapedPattern = EscapeCSharpRegexString(switchCase.Pattern!);
            var schemaName = switchCase.TypeName;

            if (isFirstCase)
            {
                builder.AppendLine($"if (LookaheadMatchesPattern(data, @\"{escapedPattern}\"))");
                isFirstCase = false;
            }
            else
            {
                builder.AppendLine($"else if (LookaheadMatchesPattern(data, @\"{escapedPattern}\"))");
            }

            builder.AppendLine("{");
            builder.AppendLine($"    var _interp_{schemaName} = new {schemaName}();");
            builder.AppendLine($"    var _result_{schemaName} = _interp_{schemaName}.ParseAt(data, _parsePosition);");
            builder.AppendLine($"    _parsePosition = _interp_{schemaName}.Position;");
            
            var matchedSchema = _registry.Schemas.FirstOrDefault(s =>
                string.Equals(s.Name, schemaName, StringComparison.OrdinalIgnoreCase));
            if (matchedSchema?.Node is TextSchemaNode matchedTextNode)
            {
                foreach (var f in matchedTextNode.Fields)
                {
                    if (!f.IsDiscard)
                        builder.AppendLine($"    {dictVar}[\"{f.Name}\"] = _result_{schemaName}.{EscapeCSharpIdentifier(f.Name)};");
                }
            }
            builder.AppendLine("}");
        }

        if (defaultCase != null)
        {
            var schemaName = defaultCase.TypeName;
            if (!isFirstCase) builder.AppendLine("else");
            builder.AppendLine("{");
            builder.AppendLine($"    var _interp_{schemaName} = new {schemaName}();");
            builder.AppendLine($"    var _result_{schemaName} = _interp_{schemaName}.ParseAt(data, _parsePosition);");
            builder.AppendLine($"    _parsePosition = _interp_{schemaName}.Position;");
            var matchedSchema = _registry.Schemas.FirstOrDefault(s =>
                string.Equals(s.Name, schemaName, StringComparison.OrdinalIgnoreCase));
            if (matchedSchema?.Node is TextSchemaNode matchedTextNode)
            {
                foreach (var f in matchedTextNode.Fields)
                {
                    if (!f.IsDiscard)
                        builder.AppendLine($"    {dictVar}[\"{f.Name}\"] = _result_{schemaName}.{EscapeCSharpIdentifier(f.Name)};");
                }
            }
            builder.AppendLine("}");
        }
        else if (!isFirstCase)
        {
            builder.AppendLine("else");
            builder.AppendLine("{");
            builder.AppendLine(
                "    throw new System.InvalidOperationException(\"No switch case matched at position \" + _parsePosition);");
            builder.AppendLine("}");
        }

        builder.AppendLine($"var {localVar} = {expandoVar};");
        if (isDiscard) builder.AppendLine($"_ = {localVar};");

        return builder.ToString();
    }

    private static string EscapeCSharpRegexString(string value)
    {
        return value.Replace("\"", "\"\"");
    }

    private static string EscapeCSharpString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t");
    }

    private static string GenerateModifierArgs(TextFieldModifier modifiers)
    {
        var hasTrim = (modifiers & TextFieldModifier.Trim) != 0;
        var hasLTrim = (modifiers & TextFieldModifier.LTrim) != 0;
        var hasRTrim = (modifiers & TextFieldModifier.RTrim) != 0;


        if (hasTrim)
            return ", trim: true";


        var args = new List<string>();
        if (hasLTrim)
            args.Add("ltrim: true");
        if (hasRTrim)
            args.Add("rtrim: true");

        return args.Count > 0 ? ", " + string.Join(", ", args) : "";
    }

    private string GenerateFieldReadCode(FieldDefinitionNode field)
    {
        var builder = new StringBuilder();
        var localVar = GetLocalVarName(field.Name);
        var typeAnnotation = field.TypeAnnotation;

        switch (typeAnnotation)
        {
            case PrimitiveTypeNode primitiveType:
                builder.AppendLine(GeneratePrimitiveReadCode(localVar, primitiveType));
                break;

            case ByteArrayTypeNode byteArrayType:
                builder.AppendLine(GenerateByteArrayReadCode(localVar, byteArrayType));
                break;

            case StringTypeNode stringType:
                builder.AppendLine(GenerateStringReadCode(localVar, stringType));
                break;

            case BitsTypeNode bitsType:
                builder.AppendLine(GenerateBitsReadCode(localVar, bitsType));
                break;

            case SchemaReferenceTypeNode schemaRef:
                builder.AppendLine(GenerateSchemaReferenceReadCode(localVar, schemaRef));
                break;

            case ArrayTypeNode arrayType:
                builder.AppendLine(GenerateArrayReadCode(localVar, arrayType));
                break;

            case RepeatUntilTypeNode repeatUntilType:
                builder.AppendLine(GenerateRepeatUntilReadCode(localVar, repeatUntilType, field.Name));
                break;

            case AlignmentNode alignmentNode:
                builder.AppendLine(GenerateAlignmentCode(alignmentNode));
                break;

            case InlineSchemaTypeNode inlineSchema:
                builder.AppendLine(GenerateInlineSchemaReadCode(localVar, field.Name, inlineSchema));
                break;

            default:
                builder.AppendLine($"// TODO: Unsupported type annotation: {typeAnnotation.GetType().Name}");
                if (field.Name != "_")
                {
                    var clrType = GetClrTypeName(typeAnnotation);
                    builder.AppendLine($"var {localVar} = default({clrType})!;");
                }

                break;
        }

        return builder.ToString();
    }

    private string GeneratePrimitiveReadCode(string localVar, PrimitiveTypeNode primitiveType)
    {
        var readMethod = GetPrimitiveReadMethod(primitiveType);
        return $"var {localVar} = {readMethod}(data);";
    }

    private static string GetPrimitiveReadMethod(PrimitiveTypeNode primitiveType)
    {
        return primitiveType.TypeName switch
        {
            PrimitiveTypeName.Byte => "ReadByte",
            PrimitiveTypeName.SByte => "ReadSByte",
            PrimitiveTypeName.Short => primitiveType.Endianness == Endianness.LittleEndian
                ? "ReadInt16LE"
                : "ReadInt16BE",
            PrimitiveTypeName.UShort => primitiveType.Endianness == Endianness.LittleEndian
                ? "ReadUInt16LE"
                : "ReadUInt16BE",
            PrimitiveTypeName.Int => primitiveType.Endianness == Endianness.LittleEndian
                ? "ReadInt32LE"
                : "ReadInt32BE",
            PrimitiveTypeName.UInt => primitiveType.Endianness == Endianness.LittleEndian
                ? "ReadUInt32LE"
                : "ReadUInt32BE",
            PrimitiveTypeName.Long => primitiveType.Endianness == Endianness.LittleEndian
                ? "ReadInt64LE"
                : "ReadInt64BE",
            PrimitiveTypeName.ULong => primitiveType.Endianness == Endianness.LittleEndian
                ? "ReadUInt64LE"
                : "ReadUInt64BE",
            PrimitiveTypeName.Float => primitiveType.Endianness == Endianness.LittleEndian
                ? "ReadSingleLE"
                : "ReadSingleBE",
            PrimitiveTypeName.Double => primitiveType.Endianness == Endianness.LittleEndian
                ? "ReadDoubleLE"
                : "ReadDoubleBE",
            _ => throw new InvalidOperationException($"Unknown primitive type: {primitiveType.TypeName}")
        };
    }

    private string GenerateByteArrayReadCode(string localVar, ByteArrayTypeNode byteArrayType)
    {
        var sizeExpr = GenerateSizeExpression(byteArrayType.SizeExpression);
        return $"var {localVar} = ReadBytes(data, {sizeExpr});";
    }

    private string GenerateStringReadCode(string localVar, StringTypeNode stringType)
    {
        var sizeExpr = GenerateSizeExpression(stringType.SizeExpression);
        var encodingExpr = GetEncodingExpression(stringType.Encoding);

        var builder = new StringBuilder();


        var rawStringVar = stringType.AsTextSchemaName != null ? $"{localVar}_raw" : localVar;


        if (stringType.Modifiers.HasFlag(StringModifier.NullTerm))
            builder.Append($"var {rawStringVar} = ReadNullTerminatedString(data, {sizeExpr}, {encodingExpr})");
        else
            builder.Append($"var {rawStringVar} = ReadString(data, {sizeExpr}, {encodingExpr})");


        if (stringType.Modifiers.HasFlag(StringModifier.Trim))
            builder.Append(".Trim()");
        else if (stringType.Modifiers.HasFlag(StringModifier.LTrim))
            builder.Append(".TrimStart()");
        else if (stringType.Modifiers.HasFlag(StringModifier.RTrim))
            builder.Append(".TrimEnd()");

        builder.Append(";");


        if (stringType.AsTextSchemaName != null)
        {
            builder.AppendLine();
            builder.AppendLine(
                $"                var {localVar}_textInterpreter = new {stringType.AsTextSchemaName}();");
            builder.Append($"                var {localVar} = {localVar}_textInterpreter.Parse({rawStringVar});");
        }

        return builder.ToString();
    }

    private static string FormatHexLiteral(HexIntegerNode hexNode)
    {
        var value = Convert.ToInt64(hexNode.ObjValue ?? 0L);
        
        
        
        if (value > int.MaxValue && value <= uint.MaxValue)
            return $"unchecked((int){value}L)";
        return value.ToString();
    }
    private static string GetEncodingExpression(StringEncoding encoding)
    {
        return encoding switch
        {
            StringEncoding.Utf8 => "System.Text.Encoding.UTF8",
            StringEncoding.Utf16Le => "System.Text.Encoding.Unicode",
            StringEncoding.Utf16Be => "System.Text.Encoding.BigEndianUnicode",
            StringEncoding.Ascii => "System.Text.Encoding.ASCII",
            StringEncoding.Latin1 => "System.Text.Encoding.Latin1",
            StringEncoding.Ebcdic => "System.Text.Encoding.GetEncoding(37)",
            _ => "System.Text.Encoding.UTF8"
        };
    }

    private string GenerateBitsReadCode(string localVar, BitsTypeNode bitsType)
    {
        var bitCount = bitsType.BitCount;
        var castType = GetBitsClrTypeName(bitsType);
        return $"var {localVar} = ({castType})ReadBits(data, {bitCount});";
    }

    private static string GetBitsClrTypeName(BitsTypeNode bitsType)
    {
        return bitsType.BitCount switch
        {
            <= 8 => "byte",
            <= 16 => "ushort",
            <= 32 => "uint",
            _ => "ulong"
        };
    }

    private string GenerateSchemaReferenceReadCode(string localVar, SchemaReferenceTypeNode schemaRef)
    {
        var typeName = schemaRef.FullTypeName;
        var tempInterpreter = $"_{localVar}_interpreter";
        var builder = new StringBuilder();
        builder.AppendLine($"var {tempInterpreter} = new {typeName}();");
        builder.AppendLine($"var {localVar} = {tempInterpreter}.InterpretAt(data, _parsePosition);");
        builder.Append($"_parsePosition = {tempInterpreter}.BytesConsumed;");
        return builder.ToString();
    }

    private string GenerateInlineSchemaReadCode(string localVar, string fieldName, InlineSchemaTypeNode inlineSchema)
    {
        var inlineClassName = GetOrRegisterInlineSchemaClassName(fieldName, inlineSchema, null);
        var tempInterpreter = $"_{localVar}_interpreter";
        var builder = new StringBuilder();
        builder.AppendLine($"var {tempInterpreter} = new {inlineClassName}();");
        builder.Append(GenerateOuterRefAssignments(tempInterpreter, inlineSchema));
        builder.AppendLine($"var {localVar} = {tempInterpreter}.InterpretAt(data, _parsePosition);");
        builder.Append($"_parsePosition = {tempInterpreter}.BytesConsumed;");
        return builder.ToString();
    }

    private string GenerateArrayReadCode(string localVar, ArrayTypeNode arrayType)
    {
        var builder = new StringBuilder();
        var countExpr = GenerateSizeExpression(arrayType.SizeExpression);
        var elementTypeName = GetClrTypeName(arrayType.ElementType);
        var loopVar = $"_{localVar}_i";
        var tempVar = $"_{localVar}_list";

        builder.AppendLine($"var {tempVar} = new System.Collections.Generic.List<{elementTypeName}>();");
        builder.AppendLine($"for (int {loopVar} = 0; {loopVar} < {countExpr}; {loopVar}++)");
        builder.AppendLine("{");


        if (arrayType.ElementType is PrimitiveTypeNode primitiveElement)
        {
            var readMethod = GetPrimitiveReadMethod(primitiveElement);
            builder.AppendLine($"    {tempVar}.Add({readMethod}(data));");
        }
        else if (arrayType.ElementType is StringTypeNode stringElement)
        {
            var sizeExpr = GenerateSizeExpression(stringElement.SizeExpression);
            var encodingExpr = GetEncodingExpression(stringElement.Encoding);
            var elemVar = $"_{localVar}_elem";

            if (stringElement.Modifiers.HasFlag(StringModifier.NullTerm))
                builder.Append($"    var {elemVar} = ReadNullTerminatedString(data, {sizeExpr}, {encodingExpr})");
            else
                builder.Append($"    var {elemVar} = ReadString(data, {sizeExpr}, {encodingExpr})");

            if (stringElement.Modifiers.HasFlag(StringModifier.Trim))
                builder.Append(".Trim()");
            else if (stringElement.Modifiers.HasFlag(StringModifier.LTrim))
                builder.Append(".TrimStart()");
            else if (stringElement.Modifiers.HasFlag(StringModifier.RTrim))
                builder.Append(".TrimEnd()");

            builder.AppendLine(";");
            builder.AppendLine($"    {tempVar}.Add({elemVar});");
        }
        else if (arrayType.ElementType is SchemaReferenceTypeNode schemaRefElement)
        {
            var typeName = schemaRefElement.FullTypeName;
            var tempInterpreter = $"_{localVar}_elemInterpreter";
            builder.AppendLine($"    var {tempInterpreter} = new {typeName}();");
            builder.AppendLine($"    var _elem = {tempInterpreter}.InterpretAt(data, _parsePosition);");
            builder.AppendLine($"    _parsePosition = {tempInterpreter}.BytesConsumed;");
            builder.AppendLine($"    {tempVar}.Add(_elem);");
        }
        else
        {
            builder.AppendLine($"    // TODO: Unsupported array element type: {arrayType.ElementType.GetType().Name}");
        }

        builder.AppendLine("}");
        builder.AppendLine($"var {localVar} = {tempVar}.ToArray();");

        return builder.ToString();
    }

    private string GenerateRepeatUntilReadCode(string localVar, RepeatUntilTypeNode repeatUntilType, string fieldName)
    {
        var builder = new StringBuilder();
        var elementTypeName = GetClrTypeName(repeatUntilType.ElementType);
        var tempVar = $"_{localVar}_list";
        var lastElemVar = $"_{localVar}_lastElem";

        builder.AppendLine($"var {tempVar} = new System.Collections.Generic.List<{elementTypeName}>();");
        builder.AppendLine($"{elementTypeName} {lastElemVar};");
        builder.AppendLine("do");
        builder.AppendLine("{");


        if (repeatUntilType.ElementType is PrimitiveTypeNode primitiveElement)
        {
            var readMethod = GetPrimitiveReadMethod(primitiveElement);
            builder.AppendLine($"    {lastElemVar} = {readMethod}(data);");
            builder.AppendLine($"    {tempVar}.Add({lastElemVar});");
        }
        else if (repeatUntilType.ElementType is SchemaReferenceTypeNode schemaRefElement)
        {
            var typeName = schemaRefElement.FullTypeName;
            var tempInterpreter = $"_{localVar}_elemInterpreter";
            builder.AppendLine($"    var {tempInterpreter} = new {typeName}();");
            builder.AppendLine($"    {lastElemVar} = {tempInterpreter}.InterpretAt(data, _parsePosition);");
            builder.AppendLine($"    _parsePosition = {tempInterpreter}.BytesConsumed;");
            builder.AppendLine($"    {tempVar}.Add({lastElemVar});");
        }
        else
        {
            builder.AppendLine(
                $"    // TODO: Unsupported repeat until element type: {repeatUntilType.ElementType.GetType().Name}");
        }


        var conditionExpr = GenerateRepeatUntilCondition(repeatUntilType.Condition, fieldName, lastElemVar, tempVar);
        builder.AppendLine($"}} while (!({conditionExpr}));");

        builder.AppendLine($"var {localVar} = {tempVar}.ToArray();");

        return builder.ToString();
    }

    private string GenerateRepeatUntilCondition(Node condition, string fieldName, string lastElemVar, string listVar)
    {
        return GenerateRepeatUntilConditionInner(condition, fieldName, lastElemVar, listVar);
    }

    private string GenerateRepeatUntilConditionInner(Node condition, string fieldName, string lastElemVar,
        string listVar)
    {
        return condition switch
        {
            EqualityNode eq =>
                $"({GenerateRepeatUntilConditionInner(eq.Left, fieldName, lastElemVar, listVar)} == {GenerateRepeatUntilConditionInner(eq.Right, fieldName, lastElemVar, listVar)})",
            DiffNode diff =>
                $"({GenerateRepeatUntilConditionInner(diff.Left, fieldName, lastElemVar, listVar)} != {GenerateRepeatUntilConditionInner(diff.Right, fieldName, lastElemVar, listVar)})",
            GreaterNode gt =>
                $"({GenerateRepeatUntilConditionInner(gt.Left, fieldName, lastElemVar, listVar)} > {GenerateRepeatUntilConditionInner(gt.Right, fieldName, lastElemVar, listVar)})",
            GreaterOrEqualNode gte =>
                $"({GenerateRepeatUntilConditionInner(gte.Left, fieldName, lastElemVar, listVar)} >= {GenerateRepeatUntilConditionInner(gte.Right, fieldName, lastElemVar, listVar)})",
            LessNode lt =>
                $"({GenerateRepeatUntilConditionInner(lt.Left, fieldName, lastElemVar, listVar)} < {GenerateRepeatUntilConditionInner(lt.Right, fieldName, lastElemVar, listVar)})",
            LessOrEqualNode lte =>
                $"({GenerateRepeatUntilConditionInner(lte.Left, fieldName, lastElemVar, listVar)} <= {GenerateRepeatUntilConditionInner(lte.Right, fieldName, lastElemVar, listVar)})",
            AndNode andNode =>
                $"({GenerateRepeatUntilConditionInner(andNode.Left, fieldName, lastElemVar, listVar)} && {GenerateRepeatUntilConditionInner(andNode.Right, fieldName, lastElemVar, listVar)})",
            OrNode orNode =>
                $"({GenerateRepeatUntilConditionInner(orNode.Left, fieldName, lastElemVar, listVar)} || {GenerateRepeatUntilConditionInner(orNode.Right, fieldName, lastElemVar, listVar)})",
            IntegerNode intNode => intNode.ObjValue?.ToString() ?? "0",
            HexIntegerNode hexNode => FormatHexLiteral(hexNode),
            DecimalNode decNode => decNode.ObjValue?.ToString() ?? "0",

            AccessColumnNode acNode when string.Equals(acNode.Name, fieldName, StringComparison.OrdinalIgnoreCase) =>
                lastElemVar,
            AccessColumnNode acNode => GetLocalVarName(acNode.Name),
            IdentifierNode idNode when string.Equals(idNode.Name, fieldName, StringComparison.OrdinalIgnoreCase) =>
                lastElemVar,
            IdentifierNode idNode => GetLocalVarName(idNode.Name),

            DotNode dotNode when dotNode.Root is AccessColumnNode rootCol &&
                                 string.Equals(rootCol.Name, fieldName, StringComparison.OrdinalIgnoreCase) =>
                $"{lastElemVar}.{GetPropertyNameFromExpression(dotNode.Expression)}",
            DotNode dotNode when dotNode.Root is IdentifierNode rootId &&
                                 string.Equals(rootId.Name, fieldName, StringComparison.OrdinalIgnoreCase) =>
                $"{lastElemVar}.{GetPropertyNameFromExpression(dotNode.Expression)}",

            DotNode dotNode =>
                $"{GenerateRepeatUntilConditionInner(dotNode.Root, fieldName, lastElemVar, listVar)}.{GetPropertyNameFromExpression(dotNode.Expression)}",

            ArrayIndexNode arrayIndex when arrayIndex.Array is IdentifierNode arrId &&
                                           string.Equals(arrId.Name, fieldName, StringComparison.OrdinalIgnoreCase) =>
                GenerateArrayIndexExpression(listVar, arrayIndex.Index, fieldName, lastElemVar),

            ArrayIndexNode arrayIndex =>
                $"{GenerateRepeatUntilConditionInner(arrayIndex.Array, fieldName, lastElemVar, listVar)}[{GenerateRepeatUntilConditionInner(arrayIndex.Index, fieldName, lastElemVar, listVar)}]",

            AddNode add =>
                $"({GenerateRepeatUntilConditionInner(add.Left, fieldName, lastElemVar, listVar)} + {GenerateRepeatUntilConditionInner(add.Right, fieldName, lastElemVar, listVar)})",
            HyphenNode hyp =>
                $"({GenerateRepeatUntilConditionInner(hyp.Left, fieldName, lastElemVar, listVar)} - {GenerateRepeatUntilConditionInner(hyp.Right, fieldName, lastElemVar, listVar)})",
            StarNode star =>
                $"({GenerateRepeatUntilConditionInner(star.Left, fieldName, lastElemVar, listVar)} * {GenerateRepeatUntilConditionInner(star.Right, fieldName, lastElemVar, listVar)})",
            FSlashNode slash =>
                $"({GenerateRepeatUntilConditionInner(slash.Left, fieldName, lastElemVar, listVar)} / {GenerateRepeatUntilConditionInner(slash.Right, fieldName, lastElemVar, listVar)})",
            ModuloNode mod =>
                $"({GenerateRepeatUntilConditionInner(mod.Left, fieldName, lastElemVar, listVar)} % {GenerateRepeatUntilConditionInner(mod.Right, fieldName, lastElemVar, listVar)})",
            _ => condition.ToString() ?? "false"
        };
    }

    private string GenerateAlignmentCode(AlignmentNode alignmentNode)
    {
        var bits = alignmentNode.AlignmentBits;
        return $"AlignToBits(data, {bits});";
    }

    private string GenerateSizeExpression(Node sizeExpression)
    {
        if (sizeExpression is IntegerNode intNode) return intNode.ObjValue.ToString() ?? "0";

        if (sizeExpression is AccessColumnNode accessNode)
        {
            var localVar = GetLocalVarName(accessNode.Name);
            return $"(int){localVar}";
        }

        if (sizeExpression is IdentifierNode identifierNode)
        {
            var localVar = GetLocalVarName(identifierNode.Name);
            return $"(int){localVar}";
        }


        if (sizeExpression is AddNode addNode)
        {
            var left = GenerateSizeExpression(addNode.Left);
            var right = GenerateSizeExpression(addNode.Right);
            return $"({left} + {right})";
        }

        if (sizeExpression is HyphenNode hyphenNode)
        {
            var left = GenerateSizeExpression(hyphenNode.Left);
            var right = GenerateSizeExpression(hyphenNode.Right);
            return $"({left} - {right})";
        }

        if (sizeExpression is StarNode starNode)
        {
            var left = GenerateSizeExpression(starNode.Left);
            var right = GenerateSizeExpression(starNode.Right);
            return $"({left} * {right})";
        }

        if (sizeExpression is FSlashNode divNode)
        {
            var left = GenerateSizeExpression(divNode.Left);
            var right = GenerateSizeExpression(divNode.Right);
            return $"({left} / {right})";
        }

        if (sizeExpression is ModuloNode modNode)
        {
            var left = GenerateSizeExpression(modNode.Left);
            var right = GenerateSizeExpression(modNode.Right);
            return $"({left} % {right})";
        }


        return sizeExpression.ToString() ?? "0";
    }

    private static string GetClrTypeName(TypeAnnotationNode typeAnnotation)
    {
        return typeAnnotation switch
        {
            PrimitiveTypeNode p => p.TypeName switch
            {
                PrimitiveTypeName.Byte => "byte",
                PrimitiveTypeName.SByte => "sbyte",
                PrimitiveTypeName.Short => "short",
                PrimitiveTypeName.UShort => "ushort",
                PrimitiveTypeName.Int => "int",
                PrimitiveTypeName.UInt => "uint",
                PrimitiveTypeName.Long => "long",
                PrimitiveTypeName.ULong => "ulong",
                PrimitiveTypeName.Float => "float",
                PrimitiveTypeName.Double => "double",
                _ => "object"
            },
            ByteArrayTypeNode => "byte[]",
            StringTypeNode s => s.AsTextSchemaName ?? "string",
            BitsTypeNode b => GetBitsClrTypeName(b),
            SchemaReferenceTypeNode s => s.FullTypeName,
            ArrayTypeNode a => $"{GetClrTypeName(a.ElementType)}[]",
            RepeatUntilTypeNode r => $"{GetClrTypeName(r.ElementType)}[]",
            InlineSchemaTypeNode => "object",
            _ => "object"
        };
    }

    private static string GetClrTypeNameForField(SchemaFieldNode field)
    {
        return field switch
        {
            FieldDefinitionNode parsedField => GetClrTypeName(parsedField.TypeAnnotation),
            ComputedFieldNode computedField => InferComputedFieldTypeNameStatic(computedField.Expression),
            _ => "object"
        };
    }

    private string GetClrTypeNameForFieldDefinition(FieldDefinitionNode field)
    {
        if (field.TypeAnnotation is InlineSchemaTypeNode inlineSchema)
            return GetOrRegisterInlineSchemaClassName(field.Name, inlineSchema, null);
        return GetClrTypeName(field.TypeAnnotation);
    }

    private string GetClrTypeNameForFieldWithContext(SchemaFieldNode field, List<SchemaFieldNode> contextFields)
    {
        return field switch
        {
            FieldDefinitionNode parsedField when parsedField.TypeAnnotation is InlineSchemaTypeNode inlineSchema
                => GetOrRegisterInlineSchemaClassName(parsedField.Name, inlineSchema, null),
            FieldDefinitionNode parsedField => GetClrTypeName(parsedField.TypeAnnotation),
            ComputedFieldNode computedField => InferComputedFieldTypeName(computedField.Expression, contextFields),
            _ => "object"
        };
    }

    private string GetOrRegisterInlineSchemaClassName(string fieldName, InlineSchemaTypeNode inlineSchema,
        string? parentPrefix)
    {
        var className = $"Inline_{fieldName}";


        var existing = _inlineSchemas.FirstOrDefault(x => x.ClassName == className);
        if (existing.Schema == null) _inlineSchemas.Add((className, inlineSchema, parentPrefix));

        return className;
    }

    private static string InferComputedFieldTypeNameStatic(Node expression)
    {
        if (expression is EqualityNode or DiffNode or GreaterNode or GreaterOrEqualNode
            or LessNode or LessOrEqualNode or AndNode or OrNode)
            return "bool";


        if (expression is WordNode)
            return "string";


        if (expression is AccessMethodNode methodNode)
            if (methodNode.Name.Equals("ToString", StringComparison.OrdinalIgnoreCase))
                return "string";


        if (expression is AddNode addNode)
        {
            var leftType = InferComputedFieldTypeNameStatic(addNode.Left);
            var rightType = InferComputedFieldTypeNameStatic(addNode.Right);
            if (leftType == "string" || rightType == "string")
                return "string";
        }


        if (expression is AddNode or HyphenNode or StarNode or FSlashNode or ModuloNode) return "int";

        return "object";
    }

    private string InferComputedFieldTypeName(Node expression, List<SchemaFieldNode>? contextFields = null)
    {
        if (expression is EqualityNode or DiffNode or GreaterNode or GreaterOrEqualNode
            or LessNode or LessOrEqualNode or AndNode or OrNode)
            return "bool";


        if (expression is AddNode addNode)
        {
            var leftType = InferExpressionType(addNode.Left, contextFields);
            var rightType = InferExpressionType(addNode.Right, contextFields);
            if (leftType == "string" || rightType == "string")
                return "string";
        }


        if (expression is BinaryNode binaryNode && contextFields != null)
        {
            var leftType = InferOperandType(binaryNode.Left, contextFields);
            var rightType = InferOperandType(binaryNode.Right, contextFields);


            return GetWiderArithmeticType(leftType, rightType);
        }


        var returnType = expression.ReturnType;
        if (returnType != null && returnType != typeof(object) && returnType != typeof(void))
            return MapClrTypeName(returnType);


        if (expression is AddNode or HyphenNode or StarNode or FSlashNode or ModuloNode
            or BitwiseAndNode or BitwiseOrNode or BitwiseXorNode or LeftShiftNode or RightShiftNode)
            return "int";


        if (expression is WordNode)
            return "string";


        if (expression is AccessMethodNode methodNode)
            if (methodNode.Name.Equals("ToString", StringComparison.OrdinalIgnoreCase))
                return "string";


        return "object";
    }

    private string InferExpressionType(Node node, List<SchemaFieldNode>? contextFields)
    {
        return node switch
        {
            WordNode => "string",
            AccessMethodNode method when method.Name.Equals("ToString", StringComparison.OrdinalIgnoreCase) => "string",
            IntegerNode or HexIntegerNode => "int",
            DecimalNode => "decimal",
            IdentifierNode id => contextFields?.FirstOrDefault(f =>
                f.Name.Equals(id.Name, StringComparison.OrdinalIgnoreCase)) is { } field
                ? GetClrTypeNameForField(field)
                : "object",
            AddNode add => InferExpressionType(add.Left, contextFields) == "string" ||
                           InferExpressionType(add.Right, contextFields) == "string"
                ? "string"
                : "int",
            _ => "object"
        };
    }

    private string InferOperandType(Node operand, List<SchemaFieldNode> contextFields)
    {
        if (operand is BinaryNode binaryOp) return InferComputedFieldTypeName(binaryOp, contextFields);


        if (operand is IdentifierNode identifier)
        {
            var field = contextFields.FirstOrDefault(f =>
                f.Name.Equals(identifier.Name, StringComparison.OrdinalIgnoreCase));

            if (field != null) return GetClrTypeNameForField(field);
        }


        if (operand is IntegerNode or HexIntegerNode) return "int";

        return "object";
    }

    private static string GetWiderArithmeticType(string left, string right)
    {
        var typeOrder = new[] { "byte", "sbyte", "short", "ushort", "int", "uint", "long", "ulong", "float", "double" };
        var leftIndex = Array.IndexOf(typeOrder, left);
        var rightIndex = Array.IndexOf(typeOrder, right);

        if (leftIndex < 0 && rightIndex < 0) return "int";
        if (leftIndex < 0) return right;
        if (rightIndex < 0) return left;

        return leftIndex > rightIndex ? left : right;
    }

    private static string MapClrTypeName(Type type)
    {
        return type.Name.ToLowerInvariant() switch
        {
            "byte" => "byte",
            "sbyte" => "sbyte",
            "int16" => "short",
            "uint16" => "ushort",
            "int32" => "int",
            "uint32" => "uint",
            "int64" => "long",
            "uint64" => "ulong",
            "single" => "float",
            "double" => "double",
            "boolean" => "bool",
            "string" => "string",
            _ => "object"
        };
    }

    private string GenerateComputedFieldCode(ComputedFieldNode field, List<SchemaFieldNode>? contextFields = null)
    {
        var builder = new StringBuilder();
        var localVar = GetLocalVarName(field.Name);
        var expression = GenerateConditionExpression(field.Expression);
        var typeName = InferComputedFieldTypeName(field.Expression, contextFields);

        builder.AppendLine($"var {localVar} = ({typeName})({expression});");

        return builder.ToString();
    }

    private string GetLocalVarName(string fieldName)
    {
        if (fieldName == "_") return $"_discard{_discardCounter++}";
        return $"_{char.ToLowerInvariant(fieldName[0])}{fieldName.Substring(1)}";
    }

        private static string EscapeCSharpIdentifier(string name)
    {
        return CSharpKeywords.Contains(name) ? $"@{name}" : name;
    }

    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while"
    };
    private static string Indent(string code, int levels)
    {
        var indent = new string(' ', levels * 4);
        var lines = code.Split('\n');
        var result = new StringBuilder();
        foreach (var line in lines)
            if (string.IsNullOrWhiteSpace(line))
                result.AppendLine();
            else
                result.AppendLine(indent + line.TrimEnd('\r'));
        return result.ToString().TrimEnd();
    }

    private static bool IsReferenceType(string clrTypeName)
    {
        return clrTypeName switch
        {
            "string" => true,
            "object" => true,
            _ when clrTypeName.EndsWith("[]") => true,
            _ => false
        };
    }

    private bool IsTypeParameter(string typeName)
    {
        return _currentTypeParameters.Contains(typeName, StringComparer.Ordinal);
    }

    private string GenerateConditionExpression(Node condition)
    {
        return condition switch
        {
            EqualityNode eq => $"({GenerateConditionExpression(eq.Left)} == {GenerateConditionExpression(eq.Right)})",
            DiffNode diff => $"({GenerateConditionExpression(diff.Left)} != {GenerateConditionExpression(diff.Right)})",
            GreaterNode gt => $"({GenerateConditionExpression(gt.Left)} > {GenerateConditionExpression(gt.Right)})",
            GreaterOrEqualNode gte =>
                $"({GenerateConditionExpression(gte.Left)} >= {GenerateConditionExpression(gte.Right)})",
            LessNode lt => $"({GenerateConditionExpression(lt.Left)} < {GenerateConditionExpression(lt.Right)})",
            LessOrEqualNode lte =>
                $"({GenerateConditionExpression(lte.Left)} <= {GenerateConditionExpression(lte.Right)})",
            AndNode andNode =>
                $"({GenerateConditionExpression(andNode.Left)} && {GenerateConditionExpression(andNode.Right)})",
            OrNode orNode =>
                $"({GenerateConditionExpression(orNode.Left)} || {GenerateConditionExpression(orNode.Right)})",
            IntegerNode intNode => intNode.ObjValue?.ToString() ?? "0",
            DecimalNode decNode => decNode.ObjValue?.ToString() ?? "0",
            WordNode wordNode => $"\"{EscapeString(wordNode.Value)}\"",
            DotNode dotNode => GenerateDotExpression(dotNode),
            ArrayIndexNode arrayIndex => $"{GenerateConditionExpression(arrayIndex.Array)}[{GenerateConditionExpression(arrayIndex.Index)}]",
            AccessColumnNode acNode => GetLocalVarName(acNode.Name),
            IdentifierNode idNode => GetLocalVarName(idNode.Name),
            AccessMethodNode methodNode => GenerateMethodCallExpression(methodNode),
            AddNode add => $"({GenerateConditionExpression(add.Left)} + {GenerateConditionExpression(add.Right)})",
            HyphenNode hyp => $"({GenerateConditionExpression(hyp.Left)} - {GenerateConditionExpression(hyp.Right)})",
            StarNode star => $"({GenerateConditionExpression(star.Left)} * {GenerateConditionExpression(star.Right)})",
            FSlashNode slash =>
                $"({GenerateConditionExpression(slash.Left)} / {GenerateConditionExpression(slash.Right)})",
            ModuloNode mod => $"({GenerateConditionExpression(mod.Left)} % {GenerateConditionExpression(mod.Right)})",
            HexIntegerNode hexNode => FormatHexLiteral(hexNode),

            BitwiseAndNode bitwiseAnd =>
                $"({GenerateConditionExpression(bitwiseAnd.Left)} & {GenerateConditionExpression(bitwiseAnd.Right)})",
            BitwiseOrNode bitwiseOr =>
                $"({GenerateConditionExpression(bitwiseOr.Left)} | {GenerateConditionExpression(bitwiseOr.Right)})",
            BitwiseXorNode bitwiseXor =>
                $"({GenerateConditionExpression(bitwiseXor.Left)} ^ {GenerateConditionExpression(bitwiseXor.Right)})",
            LeftShiftNode leftShift =>
                $"({GenerateConditionExpression(leftShift.Left)} << {GenerateConditionExpression(leftShift.Right)})",
            RightShiftNode rightShift =>
                $"({GenerateConditionExpression(rightShift.Left)} >> {GenerateConditionExpression(rightShift.Right)})",
            _ => condition.ToString() ?? "false"
        };
    }

    private string GenerateMethodCallExpression(AccessMethodNode methodNode)
    {
        var methodName = methodNode.Name;
        var args = methodNode.Arguments?.Args ?? Array.Empty<Node>();
        var argExpressions = args.Select(GenerateConditionExpression).ToList();


        return methodName.ToLowerInvariant() switch
        {
            "tostring" when argExpressions.Count == 1 => $"{argExpressions[0]}.ToString()",
            "tostring" when argExpressions.Count == 0 => ".ToString()",
            _ => $"{methodName}({string.Join(", ", argExpressions)})"
        };
    }

    private string GenerateDotExpression(DotNode dotNode)
    {
        var root = GenerateConditionExpression(dotNode.Root);
        var property = GetPropertyNameFromExpression(dotNode.Expression);
        return $"{root}.{property}";
    }

    private string GenerateArrayIndexExpression(string listVar, Node indexExpr, string fieldName, string lastElemVar)
    {
        
        if (indexExpr is HyphenNode { Left: IntegerNode { ObjValue: int leftVal }, Right: IntegerNode { ObjValue: int rightVal } } && leftVal == 0 && rightVal > 0)
        {
            
            return $"{listVar}[{listVar}.Count - {rightVal}]";
        }

        if (indexExpr is IntegerNode intIdx)
        {
            var idx = Convert.ToInt32(intIdx.ObjValue);
            if (idx < 0) return $"{listVar}[{listVar}.Count - {-idx}]";
            return $"{listVar}[{idx}]";
        }

        
        var indexCode = GenerateSizeExpression(indexExpr);
        return $"{listVar}[{indexCode}]";
    }
    private static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    private static string GetPropertyNameFromExpression(Node expression)
    {
        return expression switch
        {
            AccessColumnNode acNode => acNode.Name,
            IdentifierNode idNode => idNode.Name,
            _ => expression.ToString() ?? "Unknown"
        };
    }

        private static HashSet<string> CollectOuterFieldReferences(InlineSchemaTypeNode inlineSchema)
    {
        var inlineFieldNames = new HashSet<string>(
            inlineSchema.Fields.Select(f => f.Name),
            StringComparer.OrdinalIgnoreCase);

        var outerRefs = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var field in inlineSchema.Fields)
        {
            if (field is not FieldDefinitionNode parsedField) continue;
            CollectFieldRefsFromTypeAnnotation(parsedField.TypeAnnotation, inlineFieldNames, outerRefs);

            if (parsedField.WhenCondition != null)
                CollectFieldRefsFromExpression(parsedField.WhenCondition, inlineFieldNames, outerRefs);
        }

        return outerRefs;
    }

    private static void CollectFieldRefsFromTypeAnnotation(TypeAnnotationNode type, HashSet<string> localNames, HashSet<string> outerRefs)
    {
        switch (type)
        {
            case StringTypeNode stringType:
                CollectFieldRefsFromExpression(stringType.SizeExpression, localNames, outerRefs);
                break;
            case ByteArrayTypeNode byteArrayType:
                CollectFieldRefsFromExpression(byteArrayType.SizeExpression, localNames, outerRefs);
                break;
            case ArrayTypeNode arrayType:
                CollectFieldRefsFromExpression(arrayType.SizeExpression, localNames, outerRefs);
                break;
        }
    }

    private static void CollectFieldRefsFromExpression(Node expr, HashSet<string> localNames, HashSet<string> outerRefs)
    {
        switch (expr)
        {
            case AccessColumnNode access:
                if (!localNames.Contains(access.Name))
                    outerRefs.Add(access.Name);
                break;
            case IdentifierNode ident:
                if (!localNames.Contains(ident.Name))
                    outerRefs.Add(ident.Name);
                break;
            case BinaryNode binary:
                CollectFieldRefsFromExpression(binary.Left, localNames, outerRefs);
                CollectFieldRefsFromExpression(binary.Right, localNames, outerRefs);
                break;
        }
    }

        private string GenerateOuterRefAssignments(string interpreterVar, InlineSchemaTypeNode inlineSchema)
    {
        var outerRefs = CollectOuterFieldReferences(inlineSchema);
        if (outerRefs.Count == 0)
            return string.Empty;

        var builder = new StringBuilder();
        foreach (var outerRef in outerRefs)
        {
            var localVar = GetLocalVarName(outerRef);
            builder.AppendLine($"{interpreterVar}.Outer{EscapeCSharpIdentifier(outerRef)} = Convert.ToInt32({localVar});");
        }
        return builder.ToString();
    }
}
