using System.Collections.Frozen;
using System.Collections.Generic;
using System.Text;
using Musoq.Parser.Nodes.InterpretationSchema;

namespace Musoq.Evaluator.Visitors;

/// <summary>
///     Generates C# interpreter classes from binary and text schema AST nodes.
///     The generated classes inherit from BytesInterpreterBase or TextInterpreterBase
///     and implement the actual parsing logic.
/// </summary>
public partial class InterpreterCodeGenerator
{
    private static readonly FrozenSet<string> CSharpKeywords = new[]
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while"
    }.ToFrozenSet(StringComparer.Ordinal);

    private readonly Dictionary<string, string> _generatedCode = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    ///     Tracks inline schema definitions that need nested class generation.
    ///     Key is the field name prefix (e.g., "Header"), value is the inline schema node.
    /// </summary>
    private readonly List<(string ClassName, InlineSchemaTypeNode Schema, string? ParentFieldPrefix)> _inlineSchemas =
        new();

    /// <summary>
    ///     Tracks binary switch fields that need a generated tagged-union class.
    /// </summary>
    private readonly List<(string ClassName, BinarySwitchTypeNode Switch)> _switchSchemas = new();

    private readonly SchemaRegistry _registry;
    private string _currentSchemaName = "<unknown>";
    private string[] _currentTypeParameters = Array.Empty<string>();
    private int _discardCounter;

    /// <summary>
    ///     Creates a new interpreter code generator.
    /// </summary>
    /// <param name="registry">The schema registry containing schema definitions.</param>
    public InterpreterCodeGenerator(SchemaRegistry registry)
    {
        _registry = registry ?? throw new ArgumentNullException(nameof(registry));
    }

    /// <summary>
    ///     Gets the generated source code for all schemas.
    ///     Key is schema name, value is the C# source code.
    /// </summary>
    public IReadOnlyDictionary<string, string> GeneratedCode => _generatedCode;

    /// <summary>
    ///     Generates C# code for all schemas in the registry.
    /// </summary>
    /// <param name="namespaceName">The namespace for the generated classes.</param>
    /// <returns>Complete C# source code containing all generated interpreter classes.</returns>
    public string GenerateAll(string namespaceName = "Musoq.Generated.Interpreters")
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("// This code was generated by Musoq Interpretation Schema code generator.");
        builder.AppendLine("// Do not modify this file directly.");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Buffers.Binary;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Dynamic;");
        builder.AppendLine("using Musoq.Schema.Interpreters;");
        builder.AppendLine();
        builder.AppendLine(System.Globalization.CultureInfo.InvariantCulture, $"namespace {namespaceName}");
        builder.AppendLine("{");

        foreach (var registration in _registry.Schemas)
            if (registration.Node is BinarySchemaNode binarySchema)
            {
                _inlineSchemas.Clear();
                _switchSchemas.Clear();
                var classCode = GenerateBinaryInterpreterClass(binarySchema);
                _generatedCode[registration.Name] = classCode;
                builder.AppendLine(Indent(classCode, 1));
                builder.AppendLine();

                foreach (var (inlineClassName, inlineSchema, _) in _inlineSchemas)
                {
                    var inlineClassCode = GenerateInlineSchemaNestedClass(inlineClassName, inlineSchema);
                    builder.AppendLine(Indent(inlineClassCode, 1));
                    builder.AppendLine();
                }

                foreach (var (switchClassName, switchType) in _switchSchemas)
                {
                    var switchClassCode = GenerateSwitchNestedClass(switchClassName, switchType);
                    builder.AppendLine(Indent(switchClassCode, 1));
                    builder.AppendLine();
                }
            }
            else if (registration.Node is TextSchemaNode textSchema)
            {
                var classCode = GenerateTextInterpreterClass(textSchema);
                _generatedCode[registration.Name] = classCode;
                builder.AppendLine(Indent(classCode, 1));
                builder.AppendLine();
            }

        builder.AppendLine("}");

        return builder.ToString();
    }

    private string GetLocalVarName(string fieldName)
    {
        if (fieldName == "_") return $"_discard{_discardCounter++}";
        return $"_{char.ToLowerInvariant(fieldName[0])}{fieldName.Substring(1)}";
    }

    private static string EscapeCSharpIdentifier(string name)
    {
        return CSharpKeywords.Contains(name) ? $"@{name}" : name;
    }

    private static string Indent(string code, int levels)
    {
        var indent = new string(' ', levels * 4);
        var lines = code.Split('\n');
        var result = new StringBuilder();
        foreach (var line in lines)
            if (string.IsNullOrWhiteSpace(line))
                result.AppendLine();
            else
                result.AppendLine(indent + line.TrimEnd('\r'));
        return result.ToString().TrimEnd();
    }

}
