using System.Text;
using Microsoft.Extensions.Logging.Abstractions;
using Musoq.Parser.Diagnostics;
using Musoq.Schema;
using Musoq.Schema.Optimization;

namespace Musoq.Examples.DataSources.Csv.Tests;

[TestClass]
public sealed class CsvFileSourceStreamingTests : CsvExampleTestBase
{
    [TestMethod]
    public void Execution_WhenCsvHasHeader_ShouldMapByHeaderAndConvertTypes()
    {
        var path = WriteTempCsv(
            "Name,Amount,When\n" +
            "Ada,\"12,50\",31.12.2023\n" +
            "Bob,\"2,40\",01.01.2024\n");
        var query =
            "table CsvShape { Name: string, Amount: decimal culture 'pl-PL', EventDate: datetime source name 'When' format 'dd.MM.yyyy' };" +
            "couple #csv.file with table CsvShape as Rows;" +
            $"select Name, Amount, EventDate from Rows({SqlString(path)}, true) order by Name";

        var table = Run(query);

        Assert.AreEqual(2, table.Count);
        Assert.AreEqual("Ada", table[0][0]);
        Assert.AreEqual(12.50m, table[0][1]);
        Assert.AreEqual(new DateTime(2023, 12, 31), table[0][2]);
        Assert.AreEqual("Bob", table[1][0]);
        Assert.AreEqual(2.40m, table[1][1]);
        Assert.AreEqual(new DateTime(2024, 1, 1), table[1][2]);
    }

    [TestMethod]
    public void Execution_WhenCsvHasNoHeader_ShouldMapByOrdinalAndSourceIndex()
    {
        var path = WriteTempCsv("1,Ada,ignored\n2,Bob,ignored\n");
        var query =
            "table CsvShape { Id: int, Name: string source index '1' };" +
            "couple #csv.file with table CsvShape as Rows;" +
            $"select Id, Name from Rows({SqlString(path)}) order by Id";

        var table = Run(query);

        Assert.AreEqual(2, table.Count);
        Assert.AreEqual(1, table[0][0]);
        Assert.AreEqual("Ada", table[0][1]);
        Assert.AreEqual(2, table[1][0]);
        Assert.AreEqual("Bob", table[1][1]);
    }

    [TestMethod]
    public void Execution_WhenCsvContainsQuotedAndMultilineFields_ShouldParseRecords()
    {
        var path = WriteTempCsv("Name,Note\n\"Jane \"\"JJ\"\"\",\"Line 1\nLine 2\"\n");
        var query =
            "table CsvShape { Name: string, Note: string };" +
            "couple #csv.file with table CsvShape as Rows;" +
            $"select Name, Note from Rows({SqlString(path)}, true)";

        var table = Run(query);

        Assert.AreEqual(1, table.Count);
        Assert.AreEqual("Jane \"JJ\"", table[0][0]);
        Assert.AreEqual("Line 1\nLine 2", table[0][1]);
    }

    [TestMethod]
    public void Execution_WhenCsvHasNullableOrMissingFields_ShouldReturnNull()
    {
        var path = WriteTempCsv("Name,Amount,Count\nAda,,\nBob,12.5\n");
        var query =
            "table CsvShape { Name: string, Amount: decimal?, Count: int? };" +
            "couple #csv.file with table CsvShape as Rows;" +
            $"select Name, Amount, Count from Rows({SqlString(path)}, true) order by Name";

        var table = Run(query);

        Assert.AreEqual(2, table.Count);
        Assert.AreEqual("Ada", table[0][0]);
        Assert.IsNull(table[0][1]);
        Assert.IsNull(table[0][2]);
        Assert.AreEqual("Bob", table[1][0]);
        Assert.AreEqual(12.5m, table[1][1]);
        Assert.IsNull(table[1][2]);
    }

    [TestMethod]
    public void Execution_WhenCsvFileIsEmpty_ShouldReturnNoRows()
    {
        var path = WriteTempCsv(string.Empty);
        var query =
            "table CsvShape { Name: string };" +
            "couple #csv.file with table CsvShape as Rows;" +
            $"select Name from Rows({SqlString(path)})";

        var table = Run(query);

        Assert.AreEqual(0, table.Count);
    }

    [TestMethod]
    public void Execution_WhenCsvFileHasOnlyHeader_ShouldReturnNoRows()
    {
        var path = WriteTempCsv("Name,Amount\n");
        var query =
            "table CsvShape { Name: string, Amount: int };" +
            "couple #csv.file with table CsvShape as Rows;" +
            $"select Name, Amount from Rows({SqlString(path)}, true)";

        var table = Run(query);

        Assert.AreEqual(0, table.Count);
    }

    [TestMethod]
    public void Execution_WhenSkipRowsAreDeclared_ShouldReadHeaderAfterSkippedRows()
    {
        var path = WriteTempCsv(
            "generated by export\n" +
            "created 2024-01-01\n" +
            "Name,Amount\n" +
            "Ada,12\n");
        var query =
            "table CsvShape { Name: string, Amount: int };" +
            "couple #csv.file with table CsvShape as Rows;" +
            $"select Name, Amount from Rows({SqlString(path)}, true, 2)";

        var table = Run(query);

        Assert.AreEqual(1, table.Count);
        Assert.AreEqual("Ada", table[0][0]);
        Assert.AreEqual(12, table[0][1]);
    }

    [TestMethod]
    public void Execution_WhenEncodingAndTrimModifiersAreDeclared_ShouldReadFileWithSingleEncoding()
    {
        var path = WriteTempCsv("Name\n  Lodz  \n", new UnicodeEncoding(false, false));
        var query =
            "table CsvShape { Name: string encoding 'utf-16le' trim };" +
            "couple #csv.file with table CsvShape as Rows;" +
            $"select Name from Rows({SqlString(path)}, true)";

        var table = Run(query);

        Assert.AreEqual(1, table.Count);
        Assert.AreEqual("Lodz", table[0][0]);
    }

    [TestMethod]
    public void Compile_WhenEncodingModifiersConflict_ShouldReportContractError()
    {
        var path = WriteTempCsv("Name,Other\nAda,Value\n");
        var query =
            "table CsvShape { Name: string encoding 'utf-8', Other: string encoding 'utf-16le' };" +
            "couple #csv.file with table CsvShape as Rows;" +
            $"select Name, Other from Rows({SqlString(path)}, true)";

        var result = CompileWithDiagnostics(query);

        Assert.IsFalse(result.Succeeded);
        var error = result.Errors.Single(item => item.Code == DiagnosticCode.MQ3071_SourceContractError);
        StringAssert.Contains(error.Message, "CsvInconsistentEncoding");
        StringAssert.Contains(error.Message, "column=Other");
        StringAssert.Contains(error.Message, "modifier=encoding");
    }

    [TestMethod]
    public void Execution_WhenRowsExceedChunkSize_ShouldReportRowsReadProgress()
    {
        var rows = string.Join("\n", Enumerable.Range(0, 35).Select(static index => $"Name{index}"));
        var path = WriteTempCsv($"Name\n{rows}\n");
        var query =
            "table CsvShape { Name: string };" +
            "couple #csv.file with table CsvShape as Rows;" +
            $"select Name from Rows({SqlString(path)}, true)";
        var progress = new List<DataSourceEventArgs>();

        var compiled = Compile(query);
        compiled.DataSourceProgress += (_, args) => progress.Add(args);
        var table = compiled.Run();

        Assert.AreEqual(35, table.Count);
        CollectionAssert.AreEqual(
            new[]
            {
                DataSourcePhase.Begin,
                DataSourcePhase.RowsRead,
                DataSourcePhase.RowsRead,
                DataSourcePhase.End
            },
            progress.Select(static item => item.Phase).ToArray());
        CollectionAssert.AreEqual(
            new long?[] { 32, 35 },
            progress
                .Where(static item => item.Phase == DataSourcePhase.RowsRead)
                .Select(static item => item.RowsProcessed)
                .ToArray());
        Assert.AreEqual(35, progress.Last().RowsProcessed);
    }

    [TestMethod]
    public void Source_WhenCancellationIsRequested_ShouldStopStreaming()
    {
        var path = WriteTempCsv("Name\nAda\n");
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();
        var context = new SourceExecutionContext(
            "cancel-query",
            SourceExecutionPlan.Empty(SourceIdentity.Empty),
            cancellation.Token,
            [Column("Name", 0, typeof(string))],
            new Dictionary<string, string>(),
            NullLogger.Instance);
        var source = new CsvFileSource(path, true, context);

        Assert.Throws<OperationCanceledException>(() => source.Chunks.SelectMany(static chunk => chunk).ToArray());
    }

    [TestMethod]
    public void Source_WhenCsvHasMalformedQuotes_ShouldThrowFormatException()
    {
        var path = WriteTempCsv("Name\n\"Ada\n");
        var context = new SourceExecutionContext(
            "malformed-query",
            SourceExecutionPlan.Empty(SourceIdentity.Empty),
            CancellationToken.None,
            [Column("Name", 0, typeof(string))],
            new Dictionary<string, string>(),
            NullLogger.Instance);
        var source = new CsvFileSource(path, true, context);

        Assert.Throws<FormatException>(() => source.Chunks.SelectMany(static chunk => chunk).ToArray());
    }
}
