using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Musoq.Evaluator.Visitors;
using Musoq.Parser;
using Musoq.Parser.Nodes.InterpretationSchema;

namespace Musoq.Evaluator.Tests;

/// <summary>
///     Tests for the InterpreterCodeGenerator and InterpreterCompilationUnit.
/// </summary>
[TestClass]
public partial class InterpreterCodeGenTests
{
    #region Code Generation Tests

    [TestMethod]
    public void GenerateAll_EmptyRegistry_ShouldGenerateEmptyNamespace()
    {
        // Arrange
        var registry = new SchemaRegistry();
        var generator = new InterpreterCodeGenerator(registry);

        // Act
        var code = generator.GenerateAll();

        // Assert
        Assert.Contains("namespace Musoq.Generated.Interpreters", code);
        Assert.Contains("// <auto-generated>", code);
    }

    #endregion

    private sealed class UnsupportedTypeAnnotationNode : TypeAnnotationNode
    {
        public override Type ClrType => typeof(object);

        public override bool IsFixedSize => false;

        public override int? FixedSizeBytes => null;

        public override Type ReturnType => typeof(object);

        public override string Id => nameof(UnsupportedTypeAnnotationNode);

        public override void Accept(IExpressionVisitor visitor)
        {
        }

        public override string ToString()
        {
            return "unsupported";
        }
    }

    #region Helper Methods

    private static FieldDefinitionNode CreatePrimitiveField(
        string name,
        PrimitiveTypeName typeName,
        Endianness endianness)
    {
        var typeNode = new PrimitiveTypeNode(typeName, endianness);
        return new FieldDefinitionNode(name, typeNode);
    }

    private static TextFieldDefinitionNode CreateTextField(
        string name,
        TextFieldType fieldType,
        string? primaryValue = null,
        string? secondaryValue = null,
        TextFieldModifier modifiers = TextFieldModifier.None)
    {
        return new TextFieldDefinitionNode(
            name,
            fieldType,
            primaryValue,
            secondaryValue,
            modifiers);
    }

    #endregion

}
