<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Musoq.Evaluator\Musoq.Evaluator.csproj" />
    <ProjectReference Include="..\Musoq.Targets.Abstractions\Musoq.Targets.Abstractions.csproj" />
    <ProjectReference Include="..\Musoq.Targets.Execution\Musoq.Targets.Execution.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Musoq.Converter.Tests" />
  </ItemGroup>
</Project>
