<Project>
  <PropertyGroup>
    <MusoqParserVersion>17.0.9-alpha.1</MusoqParserVersion>
    <MusoqPluginsVersion>17.0.9-alpha.1</MusoqPluginsVersion>
    <MusoqSchemaVersion>17.0.9-alpha.1</MusoqSchemaVersion>
    <MusoqEvaluatorVersion>17.0.9-alpha.2</MusoqEvaluatorVersion>
    <MusoqConverterVersion>17.0.9-alpha.2</MusoqConverterVersion>
  </PropertyGroup>
</Project>
