<Project>
  <PropertyGroup>
    <MusoqParserVersion>17.0.3-alpha.2</MusoqParserVersion>
    <MusoqPluginsVersion>17.0.3-alpha.2</MusoqPluginsVersion>
    <MusoqSchemaVersion>17.0.3-alpha.2</MusoqSchemaVersion>
    <MusoqEvaluatorVersion>17.0.3-alpha.3</MusoqEvaluatorVersion>
    <MusoqConverterVersion>17.0.3-alpha.3</MusoqConverterVersion>
  </PropertyGroup>
</Project>
