using System.Collections.Generic;
using Musoq.Targets.Abstractions;

namespace Musoq.Evaluator.IR.Execution;

internal static partial class ExecutionOperationCatalog
{
    private static IEnumerable<KeyValuePair<Type, ExecutionOperationId>> CreateNodeOperations()
    {
        yield return Operation<ExecutionSourceScan>("source.scan");
        yield return Operation<ExecutionInterpretSource>("source.interpret");
        yield return Operation<ExecutionEnumerableSource>("source.enumerable");
        yield return Operation<ExecutionCreateTable>("table.create");
        yield return Operation<ExecutionCreateValuesRows>("table.values.create");
        yield return Operation<ExecutionCreateRecordList>("record-list.create");
        yield return Operation<ExecutionCreateBoundedRecordList>("record-list.bounded.create");
        yield return Operation<ExecutionEnsureTableCapacity>("table.capacity.ensure");
        yield return Operation<ExecutionForEach>("control.foreach");
        yield return Operation<ExecutionForEachWithOrdinality>("control.foreach.ordinality");
        yield return Operation<ExecutionScopedBlock>("control.scope");
        yield return Operation<ExecutionForEachIndexed>("control.foreach.indexed");
        yield return Operation<ExecutionParallelBlock>("control.parallel");
        yield return Operation<ExecutionFusedCteProducer>("cte.producer.fused");
        yield return Operation<ExecutionLet>("variable.let");
        yield return Operation<ExecutionHoistCandidateLet>("optimizer.hoist-candidate");
        yield return Operation<ExecutionAssign>("variable.assign");
        yield return Operation<ExecutionCreateBooleanArray>("array.boolean.create");
        yield return Operation<ExecutionArrayAssign>("array.assign");
        yield return Operation<ExecutionContinue>("control.continue");
        yield return Operation<ExecutionContinueIf>("control.continue-if");
        yield return Operation<ExecutionBreak>("control.break");
        yield return Operation<ExecutionAdaptExpando>("row.adapt-expando");
        yield return Operation<ExecutionCreateObject>("object.create");
        yield return Operation<ExecutionMethodTargetDeclarationCandidate>("optimizer.method-target-declaration");
        yield return Operation<ExecutionIf>("control.if");
        yield return Operation<ExecutionCreateGeneratedRow>("row.generated.create");
        yield return Operation<ExecutionAppendRow>("table.row.append");
        yield return Operation<ExecutionAppendExistingRow>("table.row.append-existing");
        yield return Operation<ExecutionAppendRecord>("record-list.append");
        yield return Operation<ExecutionMaterializeList>("collection.materialize");
        yield return Operation<ExecutionMaterializeFilteredList>("collection.materialize-filtered");
        yield return Operation<ExecutionMaterializeExpandoList>("collection.materialize-expando");
        yield return Operation<ExecutionSetOperation>("set.operation");
        yield return Operation<ExecutionDistinctTable>("table.distinct");
        yield return Operation<ExecutionSortTable>("table.sort");
        yield return Operation<ExecutionTopNTable>("table.top");
        yield return Operation<ExecutionTopOffsetTable>("table.top-offset");
        yield return Operation<ExecutionSkipTable>("table.skip");
        yield return Operation<ExecutionTakeTable>("table.take");
        yield return Operation<ExecutionSliceTable>("table.slice");
        yield return Operation<ExecutionProjectTable>("table.project");
        yield return Operation<ExecutionOrderRecordList>("record-list.order");
        yield return Operation<ExecutionMaterializeRecordListToTable>("record-list.to-table");
        yield return Operation<ExecutionStoreTable>("cte.table.store");
        yield return Operation<ExecutionRelatedCtePhase>("cte.phase.related");
        yield return Operation<ExecutionReturnDesc>("return.desc");
        yield return Operation<ExecutionReturnTable>("return.table");
        yield return Operation<ExecutionCreateAggregateLibrary>("aggregate.library.create");
        yield return Operation<ExecutionCreateAggregateContext>("aggregate.context.create");
        yield return Operation<ExecutionEnsureAggregateGroup>("aggregate.group.ensure");
        yield return Operation<ExecutionCreateSingleKeyAggregateContext>("aggregate.single-key.context.create");
        yield return Operation<ExecutionGetOrAddSingleKeyAggregateGroup>("aggregate.single-key.group.get-or-add");
        yield return Operation<ExecutionParallelSingleKeyAggregateLoop>("aggregate.single-key.parallel-loop");
        yield return Operation<ExecutionCreateValueTupleAggregateContext>("aggregate.tuple.context.create");
        yield return Operation<ExecutionGetOrAddValueTupleAggregateGroup>("aggregate.tuple.group.get-or-add");
        yield return Operation<ExecutionAggregateSet>("aggregate.accumulator.set");
        yield return Operation<ExecutionAggregateCapturedValueSet>("aggregate.capture.set");
        yield return Operation<ExecutionParallelFilterProjectLoop>("join.parallel-filter-project");
        yield return Operation<ExecutionCreateHashPayload>("hash.payload.create");
        yield return Operation<ExecutionWindowKernelPlan>("window.kernel-plan");
        yield return Operation<ExecutionComputeRankingWindow>("window.ranking");
        yield return Operation<ExecutionComputeOffsetWindow>("window.offset");
        yield return Operation<ExecutionComputePluginWindow>("window.plugin");
        yield return Operation<ExecutionWindowAggregateKernel>("window.aggregate");
        yield return Operation<ExecutionCreateHash>("hash.create");
        yield return Operation<ExecutionHashAdd>("hash.add");
        yield return Operation<ExecutionHashProbe>("hash.probe");
        yield return Operation<ExecutionCreateKeySet>("keyset.create");
        yield return Operation<ExecutionKeySetAdd>("keyset.add");
        yield return Operation<ExecutionKeySetProbe>("keyset.probe");
        yield return Operation<ExecutionStoreCteIndex>("cte.index.store");
        yield return Operation<ExecutionLoadCteIndex>("cte.index.load");
        yield return Operation<ExecutionCreateAsOfIndex>("asof.index.create");
        yield return Operation<ExecutionAsOfProbe>("asof.probe");
        yield return Operation<ExecutionCreateRangeIndex>("range.index.create");
        yield return Operation<ExecutionRangeProbe>("range.probe");
        yield return Operation<ExecutionSingleUsePipelineFusionCandidate>("optimizer.pipeline-fusion-candidate");
        yield return Operation<ExecutionCteReadOnceFusionCandidate>("optimizer.cte-read-once-candidate");
        yield return Operation<ExecutionCteSidecarIndexStoreCandidate>("optimizer.cte-sidecar-store-candidate");
        yield return Operation<ExecutionCteSidecarIndexLoadCandidate>("optimizer.cte-sidecar-load-candidate");
        yield return Operation<ExecutionCteSidecarIndexBuildCandidate>("optimizer.cte-sidecar-build-candidate");
        yield return Operation<ExecutionCteSidecarAppendRewriteCandidate>("optimizer.cte-sidecar-append-candidate");
        yield return Operation<ExecutionCteFusedProducerCandidate>("optimizer.cte-fused-producer-candidate");
        yield return Operation<ExecutionCteIndexOnlyStorageCandidate>("optimizer.cte-index-only-candidate");
    }
}
