title: Musoq
description: SQL Swiss Army Knife - Engine for Diverse Data Sources
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Musoq on GitHub: https://github.com/Puchaczov/Musoq

include:
  - data-sources
  - sql-syntax-of-the-tool

callouts:
  warning:
    title: Warning
    color: red
    icon: fas fa-exclamation-triangle