title: Musoq
description: SQL Swiss Army Knife - Engine for Diverse Data data-sources

remote_theme: just-the-docs/just-the-docs
markdown: kramdown
plugins:
  - jekyll-remote-theme

url: https://just-the-docs.github.io

aux_links:
  Musoq on GitHub: https://github.com/Puchaczov/Musoq

include:
  - data-sources
  - sql-syntax-of-the-tool

callouts:
  warning:
    title: Warning
    color: red
    icon: fas fa-exclamation-triangle