source 'https://rubygems.org'

gem "github-pages", "~> 231"
gem "jekyll-remote-theme"
gem "jekyll", "~> 4.3.4" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "0.10.0" # pinned to the current release
# gem "just-the-docs"        # always download the latest release
