name: Documentation

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"

jobs:
  build:
    defaults:
      run:
        working-directory: docs
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        cache-version: 0
        working-directory: '${{ github.workspace }}/docs'
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: "docs/_site/"